### ISSUE TITLE
Section pagination: find other place for navigation controls (no jumping around)

### ISSUE THREAD

**Issue by distantnative** [k-next/panel#113]
When the last page has less items than the maximum per page, the controls jump around.
This could be avoided if last page fills up with "transparent" elements until the maximum, but only if more than one page exists (so that with only one page there is no unnecessary white space).

**Comment by bastianallgeier** [comment]
I would not spend too much effort on this at the moment. Seeing it in action a couple times, I think it becomes quite obvious that we need a better place for this. It should be at the top of collections IMHO, but we need to check how we can find the space for it there.
