### ISSUE TITLE
Better solution for submitting dialogs

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#116]
We have no option to stop closing a dialog after submission. But we need this for any case when we have to validate stuff in a dialog form or similar.

**Comment by distantnative** [comment]
How about just removing `this.close()` from the `submit()` method and letting it be called from outside the dialog component, when the submit action has been succeeded? If there is an error, we could add a new method in the dialog component, that gets passed the error/validation to display it inside the dialog.
