### ISSUE TITLE
Collections: add minimum size

### ISSUE THREAD

**Issue by distantnative** [k-next/panel#153]
Add option to set minimum size, that means if the minimum size is set to 3, even when only 1 item is present, it only should take the size as if there are three elements (e.g. in Template Selector). Otherwise cards do upscale too much in some cases.

**Comment by bastianallgeier** [comment]
We could fill it up with two placeholders in that case and they can be clicked to fill them with entries. Cloud look nice.

**Comment by distantnative** [comment]
Maybe in conjunction with #113
