### ISSUE TITLE
A good global error handler

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#203]
Whenever we run into a js error that we don't catch yet, we need a good way to show that error to the user and also make it debuggable. I was also thinking about using Sentry for the Alpha.

**Comment by nocksock** [comment]
+1 for sentry. Might be a good idea having it on by default during alpha/beta and optional beyond those states?

**Comment by bastianallgeier** [comment]
Yep, sounds like a good idea!

**Comment by distantnative** [comment]
@bastianallgeier Do you want to setup the Sentry account for this?

**Comment by nocksock** [comment]
I'm going to set sentry up so that bastian will only have to change the credentials.
