### ISSUE TITLE
Use fixed dependency versions

### ISSUE THREAD

**Issue by distantnative** [k-next/panel#230]
e.g. Vue, Vuex... no just minimum versions but specific ones, so that we do not stumble accidentally in breaking changes made in a newer version of a dependency, but only update them consciously

**Comment by lukasbestle** [comment]
Isn't that what npm package locks are for?
https://docs.npmjs.com/files/package-locks

**Comment by distantnative** [comment]
Yep, I think so too

**Comment by lukasbestle** [comment]
I'm not entirely familiar with how npm does it. It doesn't automatically generate those, right? But Composer does?

I agree that we should generate such files for both npm and Composer and include them in the repo. We could then upgrade the dependency versions with each release.

**Comment by distantnative** [comment]
Sounds like a good way. At the moment it is just too easy to update dependencies accidentally or unnoticed. It should be a much more deliberate process.

**Comment by lukasbestle** [comment]
Especially because it could happen that we in the team all have different package versions (or, even worse: customers who install Kirby via package managers get different dependency versions than in our release).
