### ISSUE TITLE
New tab design looks like a drag / drop zone

### ISSUE THREAD

**Issue by eighthday** [k-next/panel#345]
Very minor visual suggestion. The current tab background looks like drop zones for files, pages etc..

Current tabs:

<img width="921" alt="screen shot 2018-05-21 at 11 49 17" src="https://user-images.githubusercontent.com/4104767/40304061-2b025120-5ced-11e8-9d75-2a5a0f3202c2.png">

With no background or border:
<img width="954" alt="screen shot 2018-05-21 at 11 49 50" src="https://user-images.githubusercontent.com/4104767/40304065-2d1dd394-5ced-11e8-93f1-310666978fe5.png">

**Comment by distantnative** [comment]
We keep all issues in the starterkit repo to have a better overview. Moved your issue there.
