### ISSUE TITLE
Uploads

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#35]
We need a universal uploader component, that can be added in any place (buttons, dropdowns, areas, etc.) and will trigger the upload window and simplify the processing of uploading stuff via the API. We also need an API mutation endpoint, which can handle the uploads.

**Comment by bastianallgeier** [comment]
I was thinking about a kirby-upload tag with certain events: 

```
<kirby-upload :multiple="true" accept="image/*" @progress="progressHandler" @success="successHandler" @error="errorHandler">
  <kirby-button icon="upload">Upload</kirby-button>
</kirby-upload>
```

We could add additional attributes for upload validation. I.e. 

```
<kirby-upload
  accept="image/jpeg"
  max-size="12MB"
  max-width="1200"
  max-height="800">
  <kirby-button icon="upload">Upload</kirby-button>
</kirby-upload>
```

**Comment by distantnative** [comment]
Seems like it isn't trivial to have file uploads via a graphql API, closest approach I found quickly: https://github.com/ivome/graphql-relay-php#mutations

And then some implementing ideas for the component: https://scotch.io/tutorials/how-to-handle-file-uploads-in-vue-2

**Comment by lukasbestle** [comment]
Regarding uploads using GraphQL: I'm pretty sure we should use multipart HTTP requests for this. 

Basically we'd send a GraphQL `query` part as usual and a part for each file in the same request.
Each of those file parts should have a randomly generated UUID as its name. This UUID can be referenced in the GraphQL mutation, which can then be used to tell the API what to do with the file.

Regarding the destination: For security reasons we shouldn't allow absolute paths. Maybe we should introduce "upload types" like `file`, `avatar` etc. Avatars are easy as they don't need a path. Files would have an additional param of a `page` and a `filename`. I think this is pretty safe.
