### ISSUE TITLE
Role Switcher Dialog

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#36]
There should be a role switcher dialog for users with a nice list of available roles, similar to what Github does. It would be great if each role could have some additional explanation what the role is all about and what it can and cannot do.

**Comment by distantnative** [comment]
As reference how Github does it:
<img width="452" alt="screen shot 2017-08-30 at 19 34 51" src="https://user-images.githubusercontent.com/3788865/29886439-5a6cbb56-8dba-11e7-93da-1153001dc8e0.png">

**Comment by bastianallgeier** [comment]
I was actually thinking about providing default roles in Kirby 3. Admin, Editor and maybe Visitor. Admin HAZ ALL THE POWERZ, Editor can edit but not adjust settings or manage users and the visitor role is only for frontend users. I'm not entirely sure about the visitor role yet, but those three were my first idea. I think it would make roles more accessible if we offer default ones. They could still be extended of course.

**Comment by distantnative** [comment]
First approach:
<img width="529" alt="screen shot 2017-09-08 at 10 06 17" src="https://user-images.githubusercontent.com/3788865/30202067-6008d4cc-947d-11e7-8926-5e6d8846f3ea.png">

**Comment by lukasbestle** [comment]
I like that UI, but we'd need support for overflow inside of that modal in case someone has many roles and they don't fit on the screen.

**Comment by distantnative** [comment]
It would already have the default overflow support of the dialog component (inside scroll).

**Comment by distantnative** [comment]
@lukasbestle What do you think about the "confirm color". Should it be the positive state (green) or rather the negative (red) to symbolize the somewhat dramatic consequences a change could cause?

**Comment by lukasbestle** [comment]
I'd say that a negative color is quite confusing for a settings change (unless the whole setting is in a red "danger zone" like on GitHub). Even more if paired with a check mark.

I'd use a checkmark, a positive color and the label "Change role".

**Comment by distantnative** [comment]
> I'd say that a negative color is quite confusing for a settings change (unless the whole setting is in a red "danger zone" like on GitHub). Even more if paired with a check mark.
> I'd use a checkmark, a positive color and the label "Change role".

Ok, sounds like a good idea 👍 

> We should also make sure that the current role is preselected in the radio field.

Already covered :)

**Comment by distantnative** [comment]
@bastianallgeier @lukasbestle 
A bit off-topic on roles in general: Considering our issues in v2, maybe the Admin and Vistor role should be unchangeable system roles that are always included. The visitor role would replace the `nobody` role from v2. And only Editor is a default role that gets added, when no custom roles are set, but excluded as soon as custom roles are defined. I think with ensuring to always have Admin and Visitor as roles, we could make sure to avoid a lot of the problems we encountered in v2. What do you think?

**Comment by lukasbestle** [comment]
We definitely always need a role without permissions at all, since 2.5.6 this is the case in v2 as well. And you are right: Why not always have an admin role with all possible permissions as well?

Important takeaways from v2: If we decide to have these roles by default, we must make sure that they also can't be overwritten by the developer as we need to be able to rely on their functions.

Regarding naming: I agree that "Visitor" is more human-friendly than "Nobody" (which is hard to understand by non-devs). Our customers wouldn't even have to change their user files as we'd fallback to the "Visitor" role anyway in case a user has been set to the now non-existing "nobody" role.

**Comment by bastianallgeier** [comment]
I think this suggestion makes a lot of sense. Unchangable admin and visitor roles as default + an modifiable editor role would also create a very nice initial setup that is easy to understand. I think we should really try to simplify permissions in general in Kirby 3. It is mighty as hell in Kirby 2 but it has too many possible edge cases and the role issue is just one of it.
