### ISSUE TITLE
Add Time Field

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#49]
The time field should be very similar to the date field and can probably inherit quite some stuff from it. Two select boxes for hours and minutes with configurable intervals for minutes, so we don't just go from 00 to 59. For AM / PM we need a third select box to toggle that and switch the hours select box from 24 hours to 12.

**Comment by fourpixels** [comment]
This would require finishing the Toggle Field (https://github.com/k-next/ui/issues/50) which I presume will require Checkbox Field (https://github.com/k-next/ui/issues/42).

How do you mark these as dependencies?

**Comment by distantnative** [comment]
At this time, we mention them in the issue/PR/comment and set the status label to blocked.

**Comment by distantnative** [comment]
Started with a first rough implementation: https://github.com/k-next/panel/commit/7621940bc145a9de82ef458845a90ef6fab4e662
Would love to hear your thoughts, ideas, improvements @fourpixels

**Comment by distantnative** [comment]
<img width="220" alt="screen shot 2017-10-13 at 13 32 57" src="https://user-images.githubusercontent.com/3788865/31544480-4946d2de-b01b-11e7-9341-c72badd7e683.png">
<img width="202" alt="screen shot 2017-10-13 at 13 34 31" src="https://user-images.githubusercontent.com/3788865/31544481-4968c556-b01b-11e7-96c6-7882417b9d5f.png">

**Comment by distantnative** [comment]
Do we really need the 12/24h switch on the field? Shouldn't it be just a blueprint option and not decided each time by the user?

<img width="222" alt="screen shot 2017-10-20 at 10 32 31" src="https://user-images.githubusercontent.com/3788865/31812075-1b1efa3c-b582-11e7-9b72-d7557790fffc.png">

**Comment by bastianallgeier** [comment]
No, the switch should definitely just be in the blueprints. Sorry if I didn't make this clear enough.
