### ISSUE TITLE
UI i18n: Short vs full locales

### ISSUE THREAD

**Issue by olach** [k-next/panel#73]
One small but annoying thing with Kirby 2 is that the Swedish translation uses a full locale ID, when a short one is only needed. So whenever I need to translate a field I have to do this:

```yaml
label:
  en: Page title
  de: Seitentitel
  sv_SE: Sidtitel
```

It would be simpler to only type `sv` for the Swedish translation here. My first thought was to suggest to change the Swedish locale from `sv_SE` to only `sv` in Transifex. But when giving it a thought, maybe we should specify all languages with the full locales instead there?

When looking at the bundled panel translations, most languages have only the language code specified. Some languages have also their country code specified. For Portuguese this is necessary because that language is spoken in both Portugal and Brazil.

The Swedish translation stands out being the only language that has a full locale ID, when actually a short would be necessary.

The English translation has the locale ID `en`. What happens when a specific translation for Australia `en_AU` is added? Should we change the original `en` to `en_US`? Or keep `en` as a default translation?

I guess this needs to be given some thoughts. The issue is two fold.

1. How should we name the locales in Transifex? Should all be full locales with both language and country codes? Or should we mix short and full locales as we do now?

2. When specifying translations in our yaml files, if we go for always full locale IDs in Transifex, should we allow specifying short locale IDs that defaults to a specific translation if two or more is found? E.g. `sv` defaults to `sv_SE` if `sv` is not found. This would solve my main issue with translations as noted above. But a problem arises if `sv_FI` is added later. What would `sv` default to? `sv_SE` or ` sv_FI`? 

Sorry for the long issue text. I would like to see a simple approach where only a short locale ID is needed in our yaml files to speed things up when coding, if that is possible.

**Comment by distantnative** [comment]
Thanks for your thoughts. Indeed locales are an interesting topic.

First of all, you talk about the locales in your yaml files. Just to clarify, that would be only a concern for the user yaml files. Indeed Transifex only concerns the output language of the Panel (e.g. labels, buttons etc.). We should not confuse it with the translations of your content files (for which in v2 you setup the languages and locales in the `config.php`). So with the Transifex locales you should only be in touch when adding a new user manually or when offering multiple languages in blueprints for help, title, labels...

Using Transifex, the locales are already defined by Transifex: https://www.transifex.com/explore/languages/
So I do not think that we could specify them in a longer form when Transifex has chosen the short form. Of course, in some cases it might be possible to not use the general English (en) but the more precise US-English (en_US). In other cases this might not be as trivial though.

And regarding your point 2 – I can't really imagine a way that does not overly complicates things but still would please the majority of users in trying to automate recognition of partial locales from yaml files.

**Comment by lukasbestle** [comment]
Transifex does not "choose" any language code, that's something we have done. For example there is both a `sv` and a `sv_SE` language.

I think we should do it like this:

1. Only use short language codes without the region specifier. For example `en`, `de` and `sv`.
2. For languages that already have multiple Panel translations (like Portuguese and Spanish), the main region (like Spanish Spanish or Portuguese Portuguese) should have the short code and the other regions should have region-specific codes.
3. The locales can be configured both with short codes *and* with long codes. If the language isn't translated to that specific locale region, the Panel will fall back to the "short" locale. If the locale region is translated at a later point, it would work out of the box.

**Comment by distantnative** [comment]
> Transifex does not "choose" any language code, that's something we have done. For example there is both a sv and a sv_SE language in Transifex.

What I meant with that, is that Transifex also includes some languages with only the short codes and no "nationalized long version".

**Comment by lukasbestle** [comment]
Well, yes. Some languages don't have any variations. That's why I propose that we default to short codes as well. :)
