### ISSUE TITLE
Refactor props binding for inputs and fields

### ISSUE THREAD

**Issue by bastianallgeier** [k-next/panel#85]
I somehow messed around here with v-bind props and now we have unwanted HTML attributes all over the place. I think we need to mixins. One for field props and one for input props

**Comment by distantnative** [comment]
Difficulty is that we would still need all Input props in all Field components. And then using `v-bind="$props"` on `kirby-field` as well as the input sub component would still created unwanted HTML attributes all over the place, wouldn't it? So do we have to get rid of `v-bind="$props"` then?

**Comment by distantnative** [comment]
Any progress we could discuss over this weekend, @fourpixels?

**Comment by fourpixels** [comment]
Sorry guys, I was out of the country (did a short free diving trip to Greece :) ) Will be back online this week.
